### ISSUE TITLE
Buen trabajo.

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcas-s3-evaluacion-intermedia-annabranco#1]
Nos animamos a dejarlo bonico?

1. Primero hay que darle un indentado a todo esto y quitarle el aspecto descuidado.
2. Está guay el uso de React.Fragment pero ya que no has metido el título que se pedía solo queda 1 elemento, el UL, así que no sería necesario. O.. metemos el título que falta.
3. Sería genial crear 1 componente más, `PokemonList`, solo para el listado: ul, li y el componente Pokemon
4. Podríamos quitar los archivos que no estamos usando ;)

**Comment by annabranco** [comment]
#### Mejorías implementadas a través de los commit 05eaa1b y 3a7e96e.

### PR #2
